apiVersion: v1
kind: Service
metadata:
  name: conjur-master
  namespace: {{ CONJUR_NAMESPACE_NAME }}
spec:
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
    - name: pg-main
      port: 5432
      protocol: TCP
      targetPort: 5432
    - name: pg-service
      port: 5433
      protocol: TCP
      targetPort: 5433

  selector: {}
